// The tile fetch/decode/draw path, run against a real .pbf with the real
// decoder. Every other suite `jest.mock`s away @mapbox/vector-tile and pbf, so
// until now this path had never executed at all.
//
// The fixture is committed and generated by scripts/generate-tile-fixture.mjs.

import fs from 'fs';
import path from 'path';
import { VectorTile } from '@mapbox/vector-tile';
import Protobuf from 'pbf';
import { MVTSource } from '../../src/MVTSource';
import { GeometryType } from '../../src/types';

const FIXTURE = fs.readFileSync(path.join(__dirname, '..', 'fixtures', 'sample.pbf'));

const decodeFixture = (): VectorTile => new VectorTile(new Protobuf(new Uint8Array(FIXTURE)));

const makeMap = (zoom = 10): any => ({
  overlayMapTypes: { getArray: () => [], removeAt: jest.fn(), push: jest.fn(), insertAt: jest.fn() },
  data: {
    addListener: () => ({ remove: jest.fn() }),
    remove: jest.fn(),
    addGeoJson: () => [],
    overrideStyle: jest.fn(),
  },
  addListener: () => ({ remove: jest.fn() }),
  setOptions: jest.fn(),
  getZoom: () => zoom,
  getBounds: () => undefined,
  getProjection: () => undefined,
});

const point = (x: number, y: number): any => ({ x, y });

/** Resolve one fetch with the fixture bytes. */
const respondWithFixture = (): jest.Mock =>
  jest.fn(() =>
    Promise.resolve({
      status: 200,
      statusText: 'OK',
      ok: true,
      arrayBuffer: () =>
        Promise.resolve(FIXTURE.buffer.slice(FIXTURE.byteOffset, FIXTURE.byteOffset + FIXTURE.byteLength)),
    }),
  );

const flush = async (): Promise<void> => {
  for (let i = 0; i < 5; i++) await Promise.resolve();
};

describe('vector tile decoding', () => {
  describe('the fixture itself', () => {
    test('is a real MVT that the upstream decoder reads', () => {
      const tile = decodeFixture();

      expect(Object.keys(tile.layers).sort()).toEqual(['buildings', 'roads']);
      expect(tile.layers.buildings.length).toBe(2);
      expect(tile.layers.roads.length).toBe(2);
    });

    test('carries the geometry types the spec defines', () => {
      const tile = decodeFixture();

      expect(tile.layers.buildings.feature(0).type).toBe(GeometryType.Polygon);
      expect(tile.layers.roads.feature(0).type).toBe(GeometryType.LineString);
      expect(tile.layers.roads.feature(1).type).toBe(GeometryType.Point);
    });

    test('round-trips properties of every scalar type', () => {
      const feature = decodeFixture().layers.buildings.feature(0);

      expect(feature.properties.name).toBe('Block A');
      expect(feature.properties.height).toBe(12);
      expect(feature.properties.active).toBe(true);
      expect(decodeFixture().layers.buildings.feature(1).properties.active).toBe(false);
    });

    test('round-trips feature ids', () => {
      expect(decodeFixture().layers.buildings.feature(0).id).toBe(1);
      expect(decodeFixture().layers.roads.feature(0).id).toBe(10);
    });

    test('decodes polygon geometry back to the coordinates it was built from', () => {
      const rings = decodeFixture().layers.buildings.feature(0).loadGeometry();

      expect(rings).toHaveLength(1);
      expect(rings[0][0]).toEqual({ x: 1024, y: 1024 });
      expect(rings[0][1]).toEqual({ x: 3072, y: 1024 });
      expect(rings[0][2]).toEqual({ x: 3072, y: 3072 });
      expect(rings[0][3]).toEqual({ x: 1024, y: 3072 });
    });

    test('decodes line geometry, including the relative cursor arithmetic', () => {
      const rings = decodeFixture().layers.roads.feature(0).loadGeometry();

      expect(rings[0]).toEqual([
        { x: 0, y: 2048 },
        { x: 2048, y: 2048 },
        { x: 4096, y: 2048 },
      ]);
    });

    test('decodes point geometry', () => {
      expect(decodeFixture().layers.roads.feature(1).loadGeometry()[0][0]).toEqual({ x: 2048, y: 2048 });
    });

    test('reports the extent the divisor is derived from', () => {
      expect(decodeFixture().layers.buildings.extent).toBe(4096);
    });
  });

  describe('MVTSource end to end, no decode mocks', () => {
    let source: MVTSource | undefined;

    beforeEach(() => {
      global.fetch = respondWithFixture() as any;
    });

    afterEach(() => {
      source?.dispose();
      source = undefined;
    });

    test('fetches, decodes and builds layers and features', async () => {
      source = new MVTSource(makeMap(), { url: 'https://tiles.test/{z}/{x}/{y}.pbf' });

      source.getTile(point(1, 2), 10, document);
      await flush();

      expect(Object.keys(source.mVTLayers).sort()).toEqual(['buildings', 'roads']);
      const stats = source.getStats();
      expect(stats.features).toBe(4);
      expect(stats.loadedTiles).toBe(1);
    });

    test('emits tileload once the real tile has been drawn', async () => {
      source = new MVTSource(makeMap(), { url: 'https://tiles.test/{z}/{x}/{y}.pbf' });
      const loaded = jest.fn();
      source.on('tileload', loaded);

      source.getTile(point(1, 2), 10, document);
      await flush();

      expect(loaded).toHaveBeenCalledWith(expect.objectContaining({ tileId: '10:1:2' }));
    });

    test('tileLoaded() resolves true against a real response', async () => {
      // C3: this could never resolve before Phase 1, and no test covered it.
      source = new MVTSource(makeMap(), { url: 'https://tiles.test/{z}/{x}/{y}.pbf' });
      source.getTile(point(1, 2), 10, document);

      await expect(source.tileLoaded(2000)).resolves.toBe(true);
    });

    test('honours visibleLayers when decoding', async () => {
      source = new MVTSource(makeMap(), {
        url: 'https://tiles.test/{z}/{x}/{y}.pbf',
        visibleLayers: ['roads'],
      });

      source.getTile(point(1, 2), 10, document);
      await flush();

      expect(Object.keys(source.mVTLayers)).toEqual(['roads']);
      expect(source.getStats().features).toBe(2);
    });

    test('a filter keeps only the features it accepts', async () => {
      source = new MVTSource(makeMap(), {
        url: 'https://tiles.test/{z}/{x}/{y}.pbf',
        filter: (feature) => feature.properties.name === 'Main Street',
      });

      source.getTile(point(1, 2), 10, document);
      await flush();

      expect(source.getStats().features).toBe(1);
    });

    test('a style function receives real decoded properties', async () => {
      const style = jest.fn(() => ({ fillStyle: 'red' }));
      source = new MVTSource(makeMap(), { url: 'https://tiles.test/{z}/{x}/{y}.pbf', style });

      source.getTile(point(1, 2), 10, document);
      await flush();

      const seen = style.mock.calls.map((c) => (c[0] as any).properties.name);
      expect(seen).toEqual(expect.arrayContaining(['Block A', 'Main Street']));
    });

    test('a custom id extractor drives feature identity', async () => {
      source = new MVTSource(makeMap(), {
        url: 'https://tiles.test/{z}/{x}/{y}.pbf',
        getIDForLayerFeature: (feature) => `n:${String(feature.properties.name)}`,
      });

      source.getTile(point(1, 2), 10, document);
      await flush();

      expect(source.getFeature('n:Block A')).toBeDefined();
      expect(source.getFeature('n:Junction')).toBeDefined();
    });

    test('caches the decoded tile and does not refetch it', async () => {
      source = new MVTSource(makeMap(), { url: 'https://tiles.test/{z}/{x}/{y}.pbf', cache: true });

      source.getTile(point(1, 2), 10, document);
      await flush();
      expect(source.getStats().cachedTiles).toBe(1);

      (global.fetch as jest.Mock).mockClear();
      source.getTile(point(1, 2), 10, document);

      expect(global.fetch).not.toHaveBeenCalled();
    });

    test('releasing a tile drops its features', async () => {
      source = new MVTSource(makeMap(), { url: 'https://tiles.test/{z}/{x}/{y}.pbf' });
      const node = source.getTile(point(1, 2), 10, document);
      await flush();
      expect(source.getStats().features).toBe(4);

      source.releaseTile(node as Element);

      expect(source.getStats().features).toBe(0);
      expect(source.getStats().visibleTiles).toBe(0);
    });

    test('a real decode survives a selection round trip', async () => {
      source = new MVTSource(makeMap(), { url: 'https://tiles.test/{z}/{x}/{y}.pbf' });
      source.getTile(point(1, 2), 10, document);
      await flush();

      const id = source.getSelectedFeatureIds();
      expect(id).toEqual([]);

      source.setSelection([1]);
      expect(source.isFeatureSelected(1)).toBe(true);
      expect(source.getSelectedFeatures()).toHaveLength(1);
      expect(source.getSelectedFeatures()[0].properties.name).toBe('Block A');
    });

    test('getFeatureBounds derives real geographic bounds from the geometry', async () => {
      // The map must report the same zoom, or _onTileResponse discards the
      // response as belonging to a different zoom level.
      source = new MVTSource(makeMap(0), { url: 'https://tiles.test/{z}/{x}/{y}.pbf' });
      source.getTile(point(0, 0), 0, document);
      await flush();

      const bounds = source.getFeatureBounds(1);

      expect(bounds).toBeDefined();
      // At zoom 0 the tile is the whole world, and the fixture polygon covers
      // its middle quarter, so the bounds must sit inside the world and be
      // non-degenerate.
      expect(bounds!.getSouthWest().lng()).toBeGreaterThan(-180);
      expect(bounds!.getNorthEast().lng()).toBeLessThan(180);
      expect(bounds!.getNorthEast().lng()).toBeGreaterThan(bounds!.getSouthWest().lng());
    });
  });
});
